git:
  depth: 5
language: node_js

os: linux

env:
  global:
    - PATH=$HOME/.yarn/bin:$PATH

install: skip
script: make -j test-ci

matrix:
  fast_finish: true
  include:
    # We test the latest version on circleci
    - node_js: "12"
    # Move `windows` build to be the third since it is slow
    - os: windows
      node_js: "node"
      env:
        # https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288/9
        - YARN_GPG=no
      cache:
        yarn: true
        directories:
          - $HOME/AppData/Local/Temp/chocolatey
      before_script: choco install make
    # Continue node_js matrix
    - node_js: "6"
    - node_js: "10"
    - node_js: "8"

jobs:
  include:
    - stage: Install Dependencies
      node_js: "node"
      script: skip
#      script: make -j bootstrap-only
      cache:
        yarn: true
      workspaces:
        create:
          name: "unbuilt"
          paths:
            - ./
    - stage: Lint And Build
      name: Lint
      node_js: "node"
      workspaces:
        use:
          - unbuilt
      git:
        clone: false
      script: ls -l
    - name: Build
      node_js: "node"
      script: make -j build-ci
      workspaces:
        use:
          - unbuilt
        create:
          name: "built"
          paths:
            - ./
      git:
        clone: false
    - stage: Tests
      name: Unit Tests on Node.js 12
      workspaces:
        use:
          - built
      git:
        clone: false
      script: make -j test-ci
      node_js: "12"
    - name: Unit Tests on Windows
      workspaces:
        use:
          - built
      git:
        clone: false
      script: make -j test-ci
      node_js: "node"
      os: windows
      cache:
        yarn: true
        directories:
          - $HOME/AppData/Local/Temp/chocolatey
      before_script: choco install make
    - name: Unit Tests on Node.js 10
      workspaces:
        use:
          - built
      git:
        clone: false
      script: make -j test-ci
      node_js: "10"
    - name: Unit Tests on Node.js 8
      workspaces:
        use:
          - built
      git:
        clone: false
      script: make -j test-ci
      node_js: "8"
    - name: Unit Tests on Node.js 6
      workspaces:
        use:
          - built
      git:
        clone: false
      script: make -j test-ci
      node_js: "6"
    - name: "Parser Flow Tests"
      node_js: "node"
      workspaces:
        use:
          - built
      git:
        clone: false
      script: make -j test-flow-ci
    - name: "Parser TypeScript Tests"
      node_js: "node"
      workspaces:
        use:
          - built
      git:
        clone: false
      script: make -j test-typescript-ci
    - name: Parser Test262 Tests
      node_js: "node"
      workspaces:
        use:
          - built
        git:
          clone: false
        script: make -j test-test262-ci


notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      # Generate with
      #     travis encrypt "babeljs:<token>#activity" --add notifications.slack.rooms
      # where <token> is from the Slack integration settings.
      secure: SrwPKRe2AiNAKRo/+2yW/x4zxbWf2FBXuBuuPkdTJVTpWe++Jin1lXYJWTKP1a1i/IbmhffBO9YZcUFbeuXJpRM083vO8VYpyuBMQRqWD+Z3o+ttPlHGOJgnj0nkIcGRk6k7PpyHNnIkixfEJDvbbg9lN1Jswb3xkL8iYIHpuFE=

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
