name: Update Test262 parser tests

on:
  workflow_dispatch:
    inputs: {}
  schedule:
    - cron: "0 0 * * 5"

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: tc39/test262
          path: build/test262
      - name: Get latest test262 version
        id: test262
        run: echo "::set-output name=sha1::$(sh ./scripts/parser-tests/get-test262-version.sh)"
      - name: Update test262
        run: |
          echo ${{ steps.test262.outputs.sha1 }} | ./scripts/parser-tests/bump-test262-version.sh
          make test-test262-update-allowlist
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update test262
          branch: update-test262-parser
          delete-branch: true
          title: "Update test262 parser tests"
          body: |
            - Update test262 to [${{ steps.test262.outputs.sha1 }}][0]
            - Auto-generated by [create-pull-request][1]

            [0]: https://github.com/tc39/test262/commit/${{ steps.test262.outputs.sha1 }}
            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            area: test262
            repo automation 🤖
