name: Update Test262 parser tests
env:
  YARN_ENABLE_SCRIPTS: false # disable post-install scripts
  YARN_NODE_LINKER: pnp # use pnp linker for better performance
on:
  workflow_dispatch:
    inputs: {}
  schedule:
    - cron: "0 0 * * 5"

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: tc39/test262
          path: build/test262
      - name: Use Node.js latest
        uses: actions/setup-node@v2-beta
        with:
          node-version: "*"
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-
      - name: Get latest test262 version
        id: test262
        run: echo "::set-output name=sha1::$(sh ./scripts/parser-tests/get-test262-version.sh)"
      - name: Update test262 commit
        run: |
          echo ${{ steps.test262.outputs.sha1 }} | ./scripts/parser-tests/bump-test262-version.sh
      - name: Build babel parser
        run: |
          yarn install --immutable --skip-builds
          yarn gulp build-rollup
      - name: Update test262 allow list
        run: |
          make test-test262-update-allowlist
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update test262
          branch: update-test262-parser
          delete-branch: true
          author: "Babel Bot <babel-bot@users.noreply.github.com>"
          committer: "Babel Bot <babel-bot@users.noreply.github.com>"
          title: "Update test262 parser tests"
          body: |
            - Update test262 to [${{ steps.test262.outputs.sha1 }}][0]
            - Auto-generated by [create-pull-request][1]

            [0]: https://github.com/tc39/test262/commit/${{ steps.test262.outputs.sha1 }}
            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            area: test262
            repo automation 🤖
